### ISSUE TITLE
CA_CERTIFICATES URLs contain unescaped '(' and ')' characters.

### ISSUE THREAD

**Issue by Cerebus** [nemonik/hands-on-DevOps#2]
```
==> toolchain: Uploading root certificates to guest instance...
==> toolchain: -- /var/folders/d1/00c_bhx55jx16p42s5rzb3ph0000gn/T/vagrant-ca-certificates20181219-62221-1m9jjxf => /etc/pki/ca-trust/source/anchors/MITRE%20BA%20NPE%20CA-3(1).crt
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mv vagrant20181219-62221-1hew1dg /etc/pki/ca-trust/source/anchors/MITRE%20BA%20NPE%20CA-3(1).crt && chown root: /etc/pki/ca-trust/source/anchors/MITRE%20BA%20NPE%20CA-3(1).crt && chmod 0644 /etc/pki/ca-trust/source/anchors/MITRE%20BA%20NPE%20CA-3(1).crt

Stdout from the command:



Stderr from the command:

bash: line 4: syntax error near unexpected token `('
bash: line 4: `mv vagrant20181219-62221-1hew1dg /etc/pki/ca-trust/source/anchors/MITRE%20BA%20NPE%20CA-3(1).crt && chown root: /etc/pki/ca-trust/source/anchors/MITRE%20BA%20NPE%20CA-3(1).crt && chmod 0644 /etc/pki/ca-trust/source/anchors/MITRE%20BA%20NPE%20CA-3(1).crt'
```

**Comment by Cerebus** [comment]
The simple fix is to change the filename from `MITRE BA NPE CA-3(1).crt` to `MITRE BA NPE CA-3.crt` and update the docs.  I can send you a PR if'n you want, but it's not really worth it.

**Comment by nemonik** [comment]
Thanks... It is odd this isn't impacting me on my Mac.   I can see how the
parentheses can be problematic, but i think think the class cover this
concern...

Let me scan through the class and cut and paste the text here.

Yes. In section 9.1's note section:


NOTE

   - The cetificate URLs need to be encoded for parenthese to work.


Son if youk look closely at the URLs for certs the parentheses are encoded
thereby addressing the problem.

http://employeeshare.mitre.org/m/mjwalsh/transfer/MITRE%20BA%20ROOT.crt,http://employeeshare.mitre.org/m/mjwalsh/transfer/MITRE%20BA%20NPE%20CA-3%281%29.crt

As are they in the set_env.sh script in the root of thr project.

All this because the original certs files have these parantheses and chose
to keep them.

-Michael

**Comment by nemonik** [comment]
I have spelling mistake in the note I need to correct...  :)
